import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font"; // 変更箇所
import "./globals.css";

// 元の変数名を維持しつつ新しい形式に変換
const geistSans = {
  variable: GeistSans.variable, // 自動でCSS変数が設定される
};

const geistMono = {
  variable: GeistMono.variable, // 自動でCSS変数が設定される
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
