name = "backend-staging"
main = "src/index.ts"
compatibility_date = "2025-04-18"

[[d1_databases]]
binding = "DB"
database_name = "shopping-db-staging"
database_id = "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy"

[vars]
JWT_SECRET = "{{ JWT_SECRET_STAGING }}"
JWT_ISSUER = "kaikyou-shop-staging"
JWT_AUDIENCE = "kaikyou-shop-users-staging"
ENVIRONMENT = "staging"
