// frontend/app/layout.tsx
import "../styles/globals.css";
import { AuthProvider } from "../components/AuthProvider";
import { NavBar } from "../components/NavBar";
//import { AuthManager } from "../components/AuthManager";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: {
    icon: "/favicon.ico", // ←ここで設定
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground">
        <AuthProvider>
          {/*<AuthManager /> */}
          <NavBar />
          <ToastContainer position="bottom-right" autoClose={3000} />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
